language_dic = {
    "FR": {
        "flag": "🇫🇷",
        "months": ["Janvier", "Février", "Mars", "Avril", "Mai", "Juin", "Juillet", "Aout", "Septembre", "Octobre", "Novembre", "Décembre"],
        "home_title": "🚄 Bienvenue sur Shinka !",
        "top_3_station_by_data": "📊 Top 3 des stations par données",
        "train_scheduled": "🚆 Trains programmés",
        "train_cancelled": "❌ Trains annulés",
        "avg_journey_time": "🚗 Temps de trajet moyen",
        "key_metrics": "📈 Données clés",
        "avg_journey_time(hours)": "Temps de trajet moyen (en heures)",
        "avg_delay_time(minutes)": "Temps de retard moyen (en minutes)",
        "next_month_prediction": "Prédiction du temps de retard moyen (en minutes)",
        "pct_delay_bigger_than_60mn": "🚨 % des retards > 60mn",
        "top_delay_cause": "⏱️ Plus grande cause de retard",
        "delay_correlation_matrix": "📌 Matrice de correlation des délais",
        "station_info": "🚉 Infos sur les stations",
        "discover_data_station": "Découvrez les données détaillées d'une station spécifique.",
        "select_station": "🔎 Sélectionnez une station",
        "data_for_station": "📍 Données pour la station : ",
        "national_train_pct": "🚆 Pourcentage de trains nationaux",
        "train_cancelled_pct": "✅ Pourcentage de trains maintenus",
        "delay_cause_pct": "❗ Plus grande cause de retard: ",
        "avg_delay": "🕐 Retard moyen",
        "comp_between_stations": "🗺️ Comparaison entre deux gares",
        "start_station": "🚉 Gare de départ",
        "end_station": "🏁 Gare d’arrivée",
        "route_from": "🧭 Trajet de ",
        "stats": "⏱️ Statistiques",
        "stats_by_month": "📅 Statistiques mensuelles",
        "select_year": "🗓️ Sélectionnez une année",
        "select_month": "📆 Sélectionnez un mois",
        "data_for_months": "🔍 Données pour",
        "pct_cancellation": "📉 Taux d'annulation",
        "home": "🏠 Accueil",
        "station_info": "🚉 Infos sur les stations",
        "station_route": "🗺️ Trajet entre les stations",
        "station_date": "📅 Date de la station",
        "total_scheduled": "📋 Total des trains programmés",
        "total_cancelled": "❌ Total des trains annulés",
        "departure_station": "🚉 Gare de départ",
        "arrival_station": "🏁 Gare d’arrivée",
        "correl_between_delay_causes": "📌 Corrélation entre les causes de retard",
        "no_route_error": "🚫 Il n'existe pas de trajet entre ces deux stations.",
        "route": "🧭 Trajet",
        "national mean": "📊 Moyenne nationale",
        "categories": "📂 Catégories",
        "minutes": "⏱️ Minutes",
        "no_data_date": "🚨 Aucune donnée pour "
    },

    "EN": {
        "flag": "🇬🇧",
        "months": ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
        "home_title": "🚄 Welcome to Shinka!",
        "top_3_station_by_data": "📊 Top 3 Stations by Data",
        "train_scheduled": "🚆 Scheduled Trains",
        "train_cancelled": "❌ Cancelled Trains",
        "avg_journey_time": "🚗 Average Journey Time",
        "key_metrics": "📈 Key Metrics",
        "avg_journey_time(hours)": "Average Journey Time (hours)",
        "avg_delay_time(minutes)": "Average Delay (minutes)",
        "next_month_prediction": "Next Month Delay Prediction (minutes)",
        "pct_delay_bigger_than_60mn": "🚨 % of Delays > 60 mins",
        "top_delay_cause": "⏱️ Top Delay Cause",
        "delay_correlation_matrix": "📌 Delay Correlation Matrix",
        "station_info": "🚉 Station Info",
        "discover_data_station": "Discover detailed data for a specific station.",
        "select_station": "🔎 Select a Station",
        "data_for_station": "📍 Data for Station: ",
        "national_train_pct": "🚆 National Train Percentage",
        "train_cancelled_pct": "✅ Maintained Train Percentage",
        "delay_cause_pct": "❗ Top Delay Cause: ",
        "avg_delay": "🕐 Average Delay",
        "comp_between_stations": "🗺️ Station Comparison",
        "start_station": "🚉 Departure Station",
        "end_station": "🏁 Arrival Station",
        "route_from": "🧭 Route from ",
        "stats": "⏱️ Statistics",
        "stats_by_month": "📅 Monthly Statistics",
        "select_year": "🗓️ Select Year",
        "select_month": "📆 Select Month",
        "data_for_months": "🔍 Data for",
        "pct_cancellation": "📉 Cancellation Rate",
        "home": "🏠 Home",
        "station_info": "🚉 Station Info",
        "station_route": "🗺️ Station Route",
        "station_date": "📅 Station Date",
        "total_scheduled": "📋 Total Scheduled Trains",
        "total_cancelled": "❌ Total Cancelled Trains",
        "departure_station": "🚉 Departure Station",
        "arrival_station": "🏁 Arrival Station",
        "correl_between_delay_causes": "📌 Correlation Between Delay Causes",
        "no_route_error": "🚫 No route exists between these two stations.",
        "route": "🧭 Route",
        "national mean": "📊 National Mean",
        "categories": "📂 Categories",
        "minutes": "⏱️ Minutes",
        "no_data_date": "🚨 No data for "
    },

    "ES": {
        "flag": "🇪🇸",
        "months": ["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"],
        "home_title": "🚄 ¡Bienvenido a Shinka!",
        "top_3_station_by_data": "📊 Top 3 estaciones por datos",
        "train_scheduled": "🚆 Trenes programados",
        "train_cancelled": "❌ Trenes cancelados",
        "avg_journey_time": "🚗 Tiempo medio de viaje",
        "key_metrics": "📈 Métricas clave",
        "avg_journey_time(hours)": "Tiempo medio de viaje (horas)",
        "avg_delay_time(minutes)": "Retraso medio (minutos)",
        "next_month_prediction": "Predicción del retraso medio del próximo mes (minutos)",
        "pct_delay_bigger_than_60mn": "🚨 % de retrasos > 60 min",
        "top_delay_cause": "⏱️ Principal causa de retraso",
        "delay_correlation_matrix": "📌 Matriz de correlación de retrasos",
        "station_info": "🚉 Información de estaciones",
        "discover_data_station": "Descubre los datos detallados de una estación específica.",
        "select_station": "🔎 Selecciona una estación",
        "data_for_station": "📍 Datos para la estación: ",
        "national_train_pct": "🚆 Porcentaje de trenes nacionales",
        "train_cancelled_pct": "✅ Porcentaje de trenes no cancelados",
        "delay_cause_pct": "❗ Principal causa de retraso: ",
        "avg_delay": "🕐 Retraso medio",
        "comp_between_stations": "🗺️ Comparación entre estaciones",
        "start_station": "🚉 Estación de salida",
        "end_station": "🏁 Estación de llegada",
        "route_from": "🧭 Ruta desde ",
        "stats": "⏱️ Estadísticas",
        "stats_by_month": "📅 Estadísticas mensuales",
        "select_year": "🗓️ Seleccionar año",
        "select_month": "📆 Seleccionar mes",
        "data_for_months": "🔍 Datos para",
        "pct_cancellation": "📉 Tasa de cancelación",
        "home": "🏠 Inicio",
        "station_info": "🚉 Información de estaciones",
        "station_route": "🗺️ Ruta entre estaciones",
        "station_date": "📅 Fecha de la estación",
        "total_scheduled": "📋 Total de trenes programados",
        "total_cancelled": "❌ Total de trenes cancelados",
        "departure_station": "🚉 Estación de salida",
        "arrival_station": "🏁 Estación de llegada",
        "correl_between_delay_causes": "📌 Correlación entre causas de retraso",
        "no_route_error": "🚫 No existe una ruta entre estas dos estaciones.",
        "route": "🧭 Ruta",
        "national mean": "📊 Media nacional",
        "categories": "📂 Categorías",
        "minutes": "⏱️ Minutos",
        "no_data_date": "🚨 No hay datos para "
    },

    "IT": {
        "flag": "🇮🇹",
        "months": ["Gennaio", "Febbraio", "Marzo", "Aprile", "Maggio", "Giugno", "Luglio", "Agosto", "Settembre", "Ottobre", "Novembre", "Dicembre"],
        "home_title": "🚄 Benvenuto su Shinka!",
        "top_3_station_by_data": "📊 Top 3 stazioni per dati",
        "train_scheduled": "🚆 Treni programmati",
        "train_cancelled": "❌ Treni cancellati",
        "avg_journey_time": "🚗 Tempo medio di viaggio",
        "key_metrics": "📈 Metriche chiave",
        "avg_journey_time(hours)": "Tempo medio di viaggio (ore)",
        "avg_delay_time(minutes)": "Ritardo medio (minuti)",
        "next_month_prediction": "Previsione del ritardo medio per il mese prossimo (minuti)",
        "pct_delay_bigger_than_60mn": "🚨 % di ritardi > 60 min",
        "top_delay_cause": "⏱️ Principale causa di ritardo",
        "delay_correlation_matrix": "📌 Matrice di correlazione dei ritardi",
        "station_info": "🚉 Info stazioni",
        "discover_data_station": "Scopri i dati dettagliati di una stazione specifica.",
        "select_station": "🔎 Seleziona una stazione",
        "data_for_station": "📍 Dati per la stazione: ",
        "national_train_pct": "🚆 Percentuale di treni nazionali",
        "train_cancelled_pct": "✅ Percentuale di treni pizzati ni cancellati",
        "delay_cause_pct": "❗ Principale causa di ritardo: ",
        "avg_delay": "🕐 Ritardo medio",
        "comp_between_stations": "🗺️ Confronto tra stazioni",
        "start_station": "🚉 Stazione di partenza",
        "end_station": "🏁 Stazione di arrivo",
        "route_from": "🧭 Percorso da ",
        "stats": "⏱️ Statistiche",
        "stats_by_month": "📅 Statistiche mensili",
        "select_year": "🗓️ Seleziona anno",
        "select_month": "📆 Seleziona mese",
        "data_for_months": "🔍 Dati per",
        "pct_cancellation": "📉 Tasso di cancellazione",
        "home": "🏠 Home",
        "station_info": "🚉 Informazioni sulle stazioni",
        "station_route": "🗺️ Percorso tra stazioni",
        "station_date": "📅 Data della stazione",
        "total_scheduled": "📋 Totale treni programmati",
        "total_cancelled": "❌ Totale treni cancellati",
        "departure_station": "🚉 Stazione di partenza",
        "arrival_station": "🏁 Stazione di arrivo",
        "correl_between_delay_causes": "📌 Correlazione tra cause di ritardo",
        "no_route_error": "🚫 Non esiste un percorso tra queste due stazioni.",
        "route": "🧭 Percorso",
        "national mean": "📊 Media nazionale",
        "categories": "📂 Categorie",
        "minutes": "⏱️ Minuti",
        "no_data_date": "🚨 Nessun dato per "
    },
        "DE": {
        "flag": "🇩🇪",
        "months": ["Januar", "Februar", "März", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "November", "Dezember"],
        "home_title": "🚄 Willkommen bei Shinka!",
        "top_3_station_by_data": "📊 Top 3 Bahnhöfe nach Daten",
        "train_scheduled": "🚆 Geplante Züge",
        "train_cancelled": "❌ Ausgefallene Züge",
        "avg_journey_time": "🚗 Durchschnittliche Reisezeit",
        "key_metrics": "📈 Wichtige Kennzahlen",
        "avg_journey_time(hours)": "Durchschnittliche Reisezeit (Stunden)",
        "avg_delay_time(minutes)": "Durchschnittliche Verspätung (Minuten)",
        "next_month_prediction": "Vorhersage der durchschnittlichen Verspätung im nächsten Monat (Minuten)",
        "pct_delay_bigger_than_60mn": "🚨 % der Verspätungen > 60 Min.",
        "top_delay_cause": "⏱️ Hauptursache der Verspätung",
        "delay_correlation_matrix": "📌 Verspätungskorrelationsmatrix",
        "station_info": "🚉 Bahnhofsinfos",
        "discover_data_station": "Entdecke detaillierte Daten zu einem bestimmten Bahnhof.",
        "select_station": "🔎 Wähle einen Bahnhof",
        "data_for_station": "📍 Daten für Bahnhof: ",
        "national_train_pct": "🚆 Anteil nationaler Züge",
        "train_cancelled_pct": "✅ Anteil ausgefallener Züge",
        "delay_cause_pct": "❗ Hauptursache der Verspätung: ",
        "avg_delay": "🕐 Durchschnittliche Verspätung",
        "comp_between_stations": "🗺️ Vergleich zwischen zwei Bahnhöfen",
        "start_station": "🚉 Abfahrtsbahnhof",
        "end_station": "🏁 Zielbahnhof",
        "route_from": "🧭 Route von ",
        "stats": "⏱️ Statistiken",
        "stats_by_month": "📅 Monatliche Statistiken",
        "select_year": "🗓️ Jahr auswählen",
        "select_month": "📆 Monat auswählen",
        "data_for_months": "🔍 Daten für",
        "pct_cancellation": "📉 Stornierungsrate",
        "home": "🏠 Startseite",
        "station_info": "🚉 Bahnhofsinfos",
        "station_route": "🗺️ Streckenverlauf zwischen Bahnhöfen",
        "station_date": "📅 Bahnhofdatum",
        "total_scheduled": "📋 Gesamtzahl der geplanten Züge",
        "total_cancelled": "❌ Gesamtzahl der ausgefallenen Züge",
        "departure_station": "🚉 Abfahrtsbahnhof",
        "arrival_station": "🏁 Zielbahnhof",
        "correl_between_delay_causes": "📌 Korrelation zwischen Verspätungsursachen",
        "no_route_error": "🚫 Es existiert keine Verbindung zwischen diesen beiden Bahnhöfen.",
        "route": "🧭 Strecke",
        "national mean": "📊 Nationaler Durchschnitt",
        "categories": "📂 Kategorien",
        "minutes": "⏱️ Minuten",
        "no_data_date": "🚨 Keine Daten für "
    }
}
